#!/bin/bash

message=""

while read -r line
do
    first_char=${line:0:1}
    if [[ $first_char =~ [[:alpha:]] ]]; then
        message="$message$first_char"
    else
        echo "$message"
        message=""
    fi
done < "$1"

echo "$message"
./decode_acrostic.sh input_file.txt

